const menu = [
  {
    id: 1,
    title: `black women's suit`,
    category: 'women',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Black suits give a notable standout to women. They give them a classy, elegant look. Fitting suits will make your friends compliment you.`,
  },
  {
    id: 2,
    title: `black men's suit`,
    category: 'men',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Men's Suits Outsmart any dress code with our perfectly coordinated men's suits. Pairing impeccable craftsmanship with timeless designs`,
  },
  {
    id: 3,
    title: 'summer dress',
    category: 'women',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `From everyday dresses in exuberant prints, comfy frocks that double as cover-ups to one-step white dresses, consider picking up a few of the best summer dresses `,
  },
  {
    id: 4,
    title: `Men's Slim Jeans`,
    category: 'men',
    price: 20.99,
    img: './images/item-4.jpg',
    desc: `Men's Jeans The building blocks of any casual outfit, our edit of men’s jeans is a worthwhile scroll.`,
  },
  {
    id: 5,
    title: `
    women's white dress`,
    category: 'women',
    price: 22.99,
    img: './images/item-5.jpg',
    desc: `From your everyday look to a formal ensemble, Dillard's has the dresses to meet your style needs.
     `,
  },
  {
    id: 6,
    title: `Women's Mini Dress`,
    category: 'women',
    price: 18.99,
    img: './images/item-6.jpg',
    desc: `Lush legs, deserve an extra special mini dress. If you’re heading out out, a party dress. `,
  },
  {
    id: 7,
    title: ' Kids Jacket Waterproof',
    category: 'kids',
    price: 8.99,
    img: './images/item-7.jpg',
    desc: ` When the temperature dips, kids can find protection from the weather, stay comfortable and look great with our collection of jackets and coats. `,
  },
  {
    id: 8,
    title: `Nike Big Kids' T-Shirt`,
    category: 'kids',
    price: 12.99,
    img: './images/item-8.jpg',
    desc: `We’ve collected some amazing examples of kids' t-shirts created by our global community of designers.  `,
  },
  {
    id: 9,
    title: 'Summer dress for a girl',
    category: 'kids',
    price: 16.99,
    img: './images/item-9.jpg',
    desc: `Crochet summer dresses for little girls are adorable and comfortable and a great reason to start learning how to crochet. It is so nice to see if your little one is  in a beautiful dress, and looking like sweet little princess.`,
  },
  {
    id: 10,
    title: 'hairpins',
    category: 'accessories',
    price: 9.99,
    img: './images/item-11.jpg',
    desc: `Hairpins are an important symbol in Chinese culture. In ancient China, hairpins were worn by men as well as women, and they were essential items for everyday hairstyling.`,
  },
];
export default menu;
